import animal1 from "./../assets/animals/animal (1).jpg"
import animal2 from "./../assets/animals/animal (2).jpg"
import animal3 from "./../assets/animals/animal (3).jpg"
import animal4 from "./../assets/animals/animal (4).jpg"
import animal5 from "./../assets/animals/animal (5).jpg"
import animal6 from "./../assets/animals/animal (6).jpg"
import animal7 from "./../assets/animals/animal (7).jpg"
import animal8 from "./../assets/animals/animal (8).jpg"
import animal9 from "./../assets/animals/animal (9).jpg"
import animal10 from "./../assets/animals/animal (10).jpg"
import animal11 from "./../assets/animals/animal (11).jpg"
import animal12 from "./../assets/animals/animal (12).jpg"
import animal13 from "./../assets/animals/animal (13).jpg"
import animal14 from "./../assets/animals/animal (14).jpg"
import animal15 from "./../assets/animals/animal (15).jpg"
import animal16 from "./../assets/animals/animal (16).jpg"
import animal17 from "./../assets/animals/animal (17).jpg"
import animal18 from "./../assets/animals/animal (18).jpg"
import animal19 from "./../assets/animals/animal (19).jpg"
import animal20 from "./../assets/animals/animal (20).jpg"
import animal21 from "./../assets/animals/animal (21).jpg"
import animal22 from "./../assets/animals/animal (22).jpg"
import animal23 from "./../assets/animals/animal (23).jpg"
import animal24 from "./../assets/animals/animal (24).jpg"

export const allColor = ["tomato", "aguamarine", "cyan", "orchid", "black", "yellowgreen", "lightsteelblue", "crimson", "lightpink", "seagreen"]
export const allAnimals = [animal1, animal2, animal3, animal4, animal5, animal6, animal7, animal8, animal9, animal10, animal11, animal12, animal13, animal14, animal15, animal16, animal17, animal18, animal19, animal20, animal21, animal22, animal23, animal24]
